package com.coral.multi.general;

public enum DatesViolation {
	RESERVATION_DATE_EQUALS_ARRIVAL_DATE, RESERVATION_DATE_FRIDAY_ARRIVAL_DATE_NEXT_SUNDAY, RESERVATION_INTERVAL_VIOLATION, OVERLAPPING_DATES
}
